on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

name: binaries

jobs:
  # release binaries
  release-bins:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - x86_64-unknown-linux-musl
        bins:
          - zerus

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dtolnay/rust-toolchain@d76c2a93c593483c9892fd8d2538734f73ed8588 # stable
        with:
          target: ${{ matrix.targets }}
      - run: cargo install cargo-quickinstall
      - run: cargo quickinstall cross
      - run: cross build --bin ${{ matrix.bins }} --locked --release --target ${{ matrix.targets }}

      - name: archive
        run: |
          tar -czvf ${{ matrix.bins }}-${{ matrix.targets }}.tar.gz \
              -C target/${{ matrix.targets }}/release/ ${{ matrix.bins }}

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: ${{ matrix.bins }}-${{ matrix.targets }}.tar.gz
          path: ${{ matrix.bins }}-${{ matrix.targets }}.tar.gz

      - name: Upload binary to release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.bins }}-${{ matrix.targets }}.tar.gz
          asset_name: ${{ matrix.bins }}-${{ matrix.targets }}.tar.gz
          tag: ${{ github.ref }}
          prerelease: true
          overwrite: true
